server:
  port: 8010
  sessionTimeout: 15
  tomcat:
    max-threads: 800
    uri-encoding: UTF-8

spring:
  application:
    name: provider

eureka:
  client:
    serviceUrl:
      defaultZone: http://root:melo@eureka8001:8001/eureka/,http://root:melo@eureka8002:8002/eureka/,http://root:melo@eureka8003:8003/eureka/

db:
  product:
    url: jdbc:mysql://localhost:3306/dev_erp?useUnicode=true&characterEncoding=utf8
    username: dev_user
    password: zxcv123

config:
  redisServer:
    - localhost:6380
    - localhost:6381
    - localhost:6382
    - localhost:6383
    - localhost:6384
    - localhost:6385